/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_8_1: THREE.Mesh;
		Object_9_1: THREE.Mesh;
		Object_10_1: THREE.Mesh;
		Object_11_1: THREE.Mesh;
		Object_12_1: THREE.Mesh;
		Object_13_1: THREE.Mesh;
		Object_14_1: THREE.Mesh;
		Object_15_1: THREE.Mesh;
		Object_16_1: THREE.Mesh;
		Object_17_1: THREE.Mesh;
		Object_0: THREE.Mesh;
		Object_18_1: THREE.Mesh;
		Object_19_1: THREE.Mesh;
		Object_20_1: THREE.Mesh;
		Object_22_1: THREE.Mesh;
		Object_23: THREE.Mesh;
		Object_24_1: THREE.Mesh;
		Object_25_1: THREE.Mesh;
		Object_26_1: THREE.Mesh;
		Object_27_1: THREE.Mesh;
		Object_1: THREE.Mesh;
		Object_28_1: THREE.Mesh;
		Object_29_1: THREE.Mesh;
		Object_30_1: THREE.Mesh;
		Object_31_1: THREE.Mesh;
		Object_32_1: THREE.Mesh;
		Object_33_1: THREE.Mesh;
		Object_35_1: THREE.Mesh;
		Object_36: THREE.Mesh;
		Object_37_1: THREE.Mesh;
		Object_2_1: THREE.Mesh;
		Object_38_1: THREE.Mesh;
		Object_39_1: THREE.Mesh;
		Object_40_1: THREE.Mesh;
		Object_41_1: THREE.Mesh;
		Object_42_1: THREE.Mesh;
		Object_43_1: THREE.Mesh;
		Object_44_1: THREE.Mesh;
		Object_45_1: THREE.Mesh;
		Object_46_1: THREE.Mesh;
		Object_47_1: THREE.Mesh;
		Object_3_1: THREE.Mesh;
		Object_48_1: THREE.Mesh;
		Object_49_1: THREE.Mesh;
		Object_50_1: THREE.Mesh;
		Object_51_1: THREE.Mesh;
		Object_52_1: THREE.Mesh;
		Object_53_1: THREE.Mesh;
		Object_54_1: THREE.Mesh;
		Object_56_1: THREE.Mesh;
		Object_57_1: THREE.Mesh;
		Object_4_1: THREE.Mesh;
		Object_58_1: THREE.Mesh;
		Object_59_1: THREE.Mesh;
		Object_60_1: THREE.Mesh;
		Object_61_1: THREE.Mesh;
		Object_62_1: THREE.Mesh;
		Object_63_1: THREE.Mesh;
		Object_64_1: THREE.Mesh;
		Object_65_1: THREE.Mesh;
		Object_66_1: THREE.Mesh;
		Object_67_1: THREE.Mesh;
		Object_5_1: THREE.Mesh;
		Object_68_1: THREE.Mesh;
		Object_69_1: THREE.Mesh;
		Object_70_1: THREE.Mesh;
		Object_71_1: THREE.Mesh;
		Object_72_1: THREE.Mesh;
		Object_73_1: THREE.Mesh;
		Object_6_1: THREE.Mesh;
		Object_7_1: THREE.Mesh;
		Cube_1: THREE.Mesh;
	};
	materials: {
		["Material.014"]: THREE.MeshStandardMaterial;
		["Material.016"]: THREE.MeshStandardMaterial;
		["Material.001"]: THREE.MeshStandardMaterial;
		["Material.007"]: THREE.MeshStandardMaterial;
		["Material.009"]: THREE.MeshStandardMaterial;
		["Material.015"]: THREE.MeshStandardMaterial;
		["Material.010"]: THREE.MeshStandardMaterial;
		["Material.028"]: THREE.MeshStandardMaterial;
		["Material.029"]: THREE.MeshStandardMaterial;
		["Material.049"]: THREE.MeshStandardMaterial;
		["Material.005"]: THREE.MeshStandardMaterial;
		["Material.023"]: THREE.MeshStandardMaterial;
		["Material.026"]: THREE.MeshStandardMaterial;
		["Material.027"]: THREE.MeshStandardMaterial;
		["Material.039"]: THREE.MeshStandardMaterial;
		["Material.034"]: THREE.MeshStandardMaterial;
		["Material.064"]: THREE.MeshStandardMaterial;
		["Material.069"]: THREE.MeshStandardMaterial;
		["Material.067"]: THREE.MeshStandardMaterial;
		["Material.066"]: THREE.MeshStandardMaterial;
		["Material.002"]: THREE.MeshStandardMaterial;
		["Material.077"]: THREE.MeshStandardMaterial;
		["Material.083"]: THREE.MeshStandardMaterial;
		["Material.078"]: THREE.MeshStandardMaterial;
		["Material.063"]: THREE.MeshStandardMaterial;
		["Material.059"]: THREE.MeshStandardMaterial;
		["Material.040"]: THREE.MeshStandardMaterial;
		["Material.062"]: THREE.MeshStandardMaterial;
		["Material.060"]: THREE.MeshStandardMaterial;
		["Material.048"]: THREE.MeshStandardMaterial;
		["Material.003"]: THREE.MeshStandardMaterial;
		["Material.050"]: THREE.MeshStandardMaterial;
		["Material.038"]: THREE.MeshStandardMaterial;
		["Material.076"]: THREE.MeshStandardMaterial;
		["Material.073"]: THREE.MeshStandardMaterial;
		["Material.068"]: THREE.MeshStandardMaterial;
		["Material.070"]: THREE.MeshStandardMaterial;
		["Material.074"]: THREE.MeshStandardMaterial;
		["Material.087"]: THREE.MeshStandardMaterial;
		["Material.072"]: THREE.MeshStandardMaterial;
		["Material.088"]: THREE.MeshStandardMaterial;
		["Material.008"]: THREE.MeshStandardMaterial;
		["Material.099"]: THREE.MeshStandardMaterial;
		["Material.101"]: THREE.MeshStandardMaterial;
		["Material.102"]: THREE.MeshStandardMaterial;
		SPEAKER: THREE.MeshStandardMaterial;
		["Material.094"]: THREE.MeshStandardMaterial;
		["Material.095"]: THREE.MeshStandardMaterial;
		["Material.089"]: THREE.MeshStandardMaterial;
		["Material.093"]: THREE.MeshStandardMaterial;
		["Material.090"]: THREE.MeshStandardMaterial;
		["Material.011"]: THREE.MeshStandardMaterial;
		["Material.092"]: THREE.MeshStandardMaterial;
		["Material.006"]: THREE.MeshStandardMaterial;
		["Material.020"]: THREE.MeshStandardMaterial;
		["Material.018"]: THREE.MeshStandardMaterial;
		["Material.022"]: THREE.MeshPhysicalMaterial;
		["Material.021"]: THREE.MeshStandardMaterial;
		["Material.037"]: THREE.MeshStandardMaterial;
		["Material.031"]: THREE.MeshPhysicalMaterial;
		["Material.013"]: THREE.MeshStandardMaterial;
		["Material.030"]: THREE.MeshStandardMaterial;
		["Material.033"]: THREE.MeshStandardMaterial;
		["Material.065"]: THREE.MeshStandardMaterial;
		["Material.061"]: THREE.MeshStandardMaterial;
		["Material.071"]: THREE.MeshStandardMaterial;
		["Material.086"]: THREE.MeshStandardMaterial;
		["Material.012"]: THREE.MeshStandardMaterial;
		["Material.017"]: THREE.MeshStandardMaterial;
		Material: THREE.MeshStandardMaterial;
	};
};

export function Stage(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("/untitled.glb") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8_1.geometry}
					material={materials["Material.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9_1.geometry}
					material={materials["Material.016"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10_1.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_11_1.geometry}
					material={materials["Material.007"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_12_1.geometry}
					material={materials["Material.009"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_13_1.geometry}
					material={materials["Material.015"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_14_1.geometry}
					material={materials["Material.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_15_1.geometry}
					material={materials["Material.028"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_16_1.geometry}
					material={materials["Material.029"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_17_1.geometry}
					material={materials["Material.049"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_0.geometry}
					material={materials["Material.005"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_18_1.geometry}
					material={materials["Material.023"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_19_1.geometry}
					material={materials["Material.026"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_20_1.geometry}
					material={materials["Material.027"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_22_1.geometry}
					material={materials["Material.039"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_23.geometry}
					material={materials["Material.034"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_24_1.geometry}
					material={materials["Material.064"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_25_1.geometry}
					material={materials["Material.069"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_26_1.geometry}
					material={materials["Material.067"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_27_1.geometry}
					material={materials["Material.066"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_1.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_28_1.geometry}
					material={materials["Material.077"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_29_1.geometry}
					material={materials["Material.083"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_30_1.geometry}
					material={materials["Material.078"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_31_1.geometry}
					material={materials["Material.063"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_32_1.geometry}
					material={materials["Material.059"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_33_1.geometry}
					material={materials["Material.040"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_35_1.geometry}
					material={materials["Material.062"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_36.geometry}
					material={materials["Material.060"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_37_1.geometry}
					material={materials["Material.048"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2_1.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_38_1.geometry}
					material={materials["Material.050"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_39_1.geometry}
					material={materials["Material.038"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_40_1.geometry}
					material={materials["Material.076"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_41_1.geometry}
					material={materials["Material.073"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_42_1.geometry}
					material={materials["Material.068"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_43_1.geometry}
					material={materials["Material.070"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_44_1.geometry}
					material={materials["Material.074"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_45_1.geometry}
					material={materials["Material.087"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_46_1.geometry}
					material={materials["Material.072"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_47_1.geometry}
					material={materials["Material.088"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_3_1.geometry}
					material={materials["Material.008"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_48_1.geometry}
					material={materials["Material.099"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_49_1.geometry}
					material={materials["Material.101"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_50_1.geometry}
					material={materials["Material.102"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_51_1.geometry}
					material={materials.SPEAKER}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_52_1.geometry}
					material={materials["Material.094"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_53_1.geometry}
					material={materials["Material.095"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_54_1.geometry}
					material={materials["Material.089"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_56_1.geometry}
					material={materials["Material.093"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_57_1.geometry}
					material={materials["Material.090"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4_1.geometry}
					material={materials["Material.011"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_58_1.geometry}
					material={materials["Material.092"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_59_1.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_60_1.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_61_1.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_62_1.geometry}
					material={materials["Material.020"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_63_1.geometry}
					material={materials["Material.018"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_64_1.geometry}
					material={materials["Material.022"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_65_1.geometry}
					material={materials["Material.021"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_66_1.geometry}
					material={materials["Material.037"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_67_1.geometry}
					material={materials["Material.031"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5_1.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_68_1.geometry}
					material={materials["Material.030"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_69_1.geometry}
					material={materials["Material.033"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_70_1.geometry}
					material={materials["Material.065"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_71_1.geometry}
					material={materials["Material.061"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_72_1.geometry}
					material={materials["Material.071"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_73_1.geometry}
					material={materials["Material.086"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6_1.geometry}
					material={materials["Material.012"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7_1.geometry}
					material={materials["Material.017"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube_1.geometry}
				material={materials.Material}
			/>
		</group>
	);
}

useGLTF.preload("/untitled.glb");

export default Stage;
