/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
	nodes: {
		Object_10: THREE.Mesh;
		Object_11: THREE.Mesh;
		Object_12: THREE.Mesh;
		Object_13: THREE.Mesh;
		Object_14: THREE.Mesh;
		Object_15: THREE.Mesh;
		Object_16: THREE.Mesh;
		Object_17: THREE.Mesh;
		Object_18: THREE.Mesh;
		Object_19: THREE.Mesh;
		Object_2: THREE.Mesh;
		Object_20: THREE.Mesh;
		Object_21: THREE.Mesh;
		Object_22: THREE.Mesh;
		Object_24: THREE.Mesh;
		Object_25: THREE.Mesh;
		Object_26: THREE.Mesh;
		Object_27: THREE.Mesh;
		Object_28: THREE.Mesh;
		Object_29: THREE.Mesh;
		Object_3: THREE.Mesh;
		Object_30: THREE.Mesh;
		Object_31: THREE.Mesh;
		Object_32: THREE.Mesh;
		Object_33: THREE.Mesh;
		Object_34: THREE.Mesh;
		Object_35: THREE.Mesh;
		Object_37: THREE.Mesh;
		Object_38: THREE.Mesh;
		Object_39: THREE.Mesh;
		Object_4: THREE.Mesh;
		Object_40: THREE.Mesh;
		Object_41: THREE.Mesh;
		Object_42: THREE.Mesh;
		Object_43: THREE.Mesh;
		Object_44: THREE.Mesh;
		Object_45: THREE.Mesh;
		Object_46: THREE.Mesh;
		Object_47: THREE.Mesh;
		Object_48: THREE.Mesh;
		Object_49: THREE.Mesh;
		Object_5: THREE.Mesh;
		Object_50: THREE.Mesh;
		Object_51: THREE.Mesh;
		Object_52: THREE.Mesh;
		Object_53: THREE.Mesh;
		Object_54: THREE.Mesh;
		Object_55: THREE.Mesh;
		Object_56: THREE.Mesh;
		Object_58: THREE.Mesh;
		Object_59: THREE.Mesh;
		Object_6: THREE.Mesh;
		Object_60: THREE.Mesh;
		Object_61: THREE.Mesh;
		Object_62: THREE.Mesh;
		Object_63: THREE.Mesh;
		Object_64: THREE.Mesh;
		Object_65: THREE.Mesh;
		Object_66: THREE.Mesh;
		Object_67: THREE.Mesh;
		Object_68: THREE.Mesh;
		Object_69: THREE.Mesh;
		Object_7: THREE.Mesh;
		Object_70: THREE.Mesh;
		Object_71: THREE.Mesh;
		Object_72: THREE.Mesh;
		Object_73: THREE.Mesh;
		Object_74: THREE.Mesh;
		Object_75: THREE.Mesh;
		Object_8: THREE.Mesh;
		Object_9: THREE.Mesh;
		Cube: THREE.Mesh;
	};
	materials: {
		["Material.014"]: THREE.MeshStandardMaterial;
		["Material.016"]: THREE.MeshStandardMaterial;
		["Material.001"]: THREE.MeshStandardMaterial;
		["Material.007"]: THREE.MeshStandardMaterial;
		["Material.009"]: THREE.MeshStandardMaterial;
		["Material.015"]: THREE.MeshStandardMaterial;
		["Material.010"]: THREE.MeshStandardMaterial;
		["Material.028"]: THREE.MeshStandardMaterial;
		["Material.029"]: THREE.MeshStandardMaterial;
		["Material.049"]: THREE.MeshStandardMaterial;
		["Material.005"]: THREE.MeshStandardMaterial;
		["Material.023"]: THREE.MeshStandardMaterial;
		["Material.026"]: THREE.MeshStandardMaterial;
		["Material.027"]: THREE.MeshStandardMaterial;
		["Material.039"]: THREE.MeshStandardMaterial;
		["Material.034"]: THREE.MeshStandardMaterial;
		["Material.064"]: THREE.MeshStandardMaterial;
		["Material.069"]: THREE.MeshStandardMaterial;
		["Material.067"]: THREE.MeshStandardMaterial;
		["Material.066"]: THREE.MeshStandardMaterial;
		["Material.002"]: THREE.MeshStandardMaterial;
		["Material.077"]: THREE.MeshStandardMaterial;
		["Material.083"]: THREE.MeshStandardMaterial;
		["Material.078"]: THREE.MeshStandardMaterial;
		["Material.063"]: THREE.MeshStandardMaterial;
		["Material.059"]: THREE.MeshStandardMaterial;
		["Material.040"]: THREE.MeshStandardMaterial;
		["Material.062"]: THREE.MeshStandardMaterial;
		["Material.060"]: THREE.MeshStandardMaterial;
		["Material.048"]: THREE.MeshStandardMaterial;
		["Material.003"]: THREE.MeshStandardMaterial;
		["Material.050"]: THREE.MeshStandardMaterial;
		["Material.038"]: THREE.MeshStandardMaterial;
		["Material.076"]: THREE.MeshStandardMaterial;
		["Material.073"]: THREE.MeshStandardMaterial;
		["Material.068"]: THREE.MeshStandardMaterial;
		["Material.070"]: THREE.MeshStandardMaterial;
		["Material.074"]: THREE.MeshStandardMaterial;
		["Material.087"]: THREE.MeshStandardMaterial;
		["Material.072"]: THREE.MeshStandardMaterial;
		["Material.088"]: THREE.MeshStandardMaterial;
		["Material.008"]: THREE.MeshStandardMaterial;
		["Material.099"]: THREE.MeshStandardMaterial;
		["Material.101"]: THREE.MeshStandardMaterial;
		["Material.102"]: THREE.MeshStandardMaterial;
		SPEAKER: THREE.MeshStandardMaterial;
		["Material.094"]: THREE.MeshStandardMaterial;
		["Material.095"]: THREE.MeshStandardMaterial;
		["Material.089"]: THREE.MeshStandardMaterial;
		["Material.093"]: THREE.MeshStandardMaterial;
		["Material.090"]: THREE.MeshStandardMaterial;
		["Material.011"]: THREE.MeshStandardMaterial;
		["Material.092"]: THREE.MeshStandardMaterial;
		["Material.006"]: THREE.MeshStandardMaterial;
		["Material.020"]: THREE.MeshStandardMaterial;
		["Material.018"]: THREE.MeshStandardMaterial;
		["Material.022"]: THREE.MeshPhysicalMaterial;
		["Material.021"]: THREE.MeshStandardMaterial;
		["Material.037"]: THREE.MeshStandardMaterial;
		["Material.031"]: THREE.MeshPhysicalMaterial;
		["Material.013"]: THREE.MeshStandardMaterial;
		["Material.030"]: THREE.MeshStandardMaterial;
		["Material.033"]: THREE.MeshStandardMaterial;
		["Material.065"]: THREE.MeshStandardMaterial;
		["Material.061"]: THREE.MeshStandardMaterial;
		["Material.071"]: THREE.MeshStandardMaterial;
		["Material.086"]: THREE.MeshStandardMaterial;
		["Material.012"]: THREE.MeshStandardMaterial;
		["Material.017"]: THREE.MeshStandardMaterial;
		Material: THREE.MeshStandardMaterial;
	};
};

export function Stage(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF("/untitled.glb") as GLTFResult;
	return (
		<group {...props} dispose={null}>
			<group rotation={[-Math.PI / 2, 0, 0]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_10.geometry}
					material={materials["Material.014"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_11.geometry}
					material={materials["Material.016"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_12.geometry}
					material={materials["Material.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_13.geometry}
					material={materials["Material.007"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_14.geometry}
					material={materials["Material.009"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_15.geometry}
					material={materials["Material.015"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_16.geometry}
					material={materials["Material.010"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_17.geometry}
					material={materials["Material.028"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_18.geometry}
					material={materials["Material.029"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_19.geometry}
					material={materials["Material.049"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_2.geometry}
					material={materials["Material.005"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_20.geometry}
					material={materials["Material.023"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_21.geometry}
					material={materials["Material.026"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_22.geometry}
					material={materials["Material.027"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_24.geometry}
					material={materials["Material.039"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_25.geometry}
					material={materials["Material.034"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_26.geometry}
					material={materials["Material.064"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_27.geometry}
					material={materials["Material.069"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_28.geometry}
					material={materials["Material.067"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_29.geometry}
					material={materials["Material.066"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_3.geometry}
					material={materials["Material.002"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_30.geometry}
					material={materials["Material.077"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_31.geometry}
					material={materials["Material.083"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_32.geometry}
					material={materials["Material.078"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_33.geometry}
					material={materials["Material.063"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_34.geometry}
					material={materials["Material.059"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_35.geometry}
					material={materials["Material.040"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_37.geometry}
					material={materials["Material.062"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_38.geometry}
					material={materials["Material.060"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_39.geometry}
					material={materials["Material.048"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_4.geometry}
					material={materials["Material.003"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_40.geometry}
					material={materials["Material.050"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_41.geometry}
					material={materials["Material.038"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_42.geometry}
					material={materials["Material.076"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_43.geometry}
					material={materials["Material.073"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_44.geometry}
					material={materials["Material.068"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_45.geometry}
					material={materials["Material.070"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_46.geometry}
					material={materials["Material.074"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_47.geometry}
					material={materials["Material.087"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_48.geometry}
					material={materials["Material.072"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_49.geometry}
					material={materials["Material.088"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_5.geometry}
					material={materials["Material.008"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_50.geometry}
					material={materials["Material.099"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_51.geometry}
					material={materials["Material.101"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_52.geometry}
					material={materials["Material.102"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_53.geometry}
					material={materials.SPEAKER}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_54.geometry}
					material={materials["Material.094"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_55.geometry}
					material={materials["Material.095"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_56.geometry}
					material={materials["Material.089"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_58.geometry}
					material={materials["Material.093"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_59.geometry}
					material={materials["Material.090"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_6.geometry}
					material={materials["Material.011"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_60.geometry}
					material={materials["Material.092"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_61.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_62.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_63.geometry}
					material={materials["Material.006"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_64.geometry}
					material={materials["Material.020"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_65.geometry}
					material={materials["Material.018"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_66.geometry}
					material={materials["Material.022"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_67.geometry}
					material={materials["Material.021"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_68.geometry}
					material={materials["Material.037"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_69.geometry}
					material={materials["Material.031"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_7.geometry}
					material={materials["Material.013"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_70.geometry}
					material={materials["Material.030"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_71.geometry}
					material={materials["Material.033"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_72.geometry}
					material={materials["Material.065"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_73.geometry}
					material={materials["Material.061"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_74.geometry}
					material={materials["Material.071"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_75.geometry}
					material={materials["Material.086"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_8.geometry}
					material={materials["Material.012"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Object_9.geometry}
					material={materials["Material.017"]}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={materials.Material}
			/>
		</group>
	);
}

useGLTF.preload("/untitled.glb");

export default Stage;
